---
title: "Intro to R: Penguins - How Do they Work?"
author: "Jeremy Allen"
date: "8/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br> <br>

```{r data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# load a package into the session for use
library(tidyverse)
library(plotly)
library(palmerpenguins)
library(gt)
library(lubridate)

# read a CSV file that is online or on disk
dat <- readr::read_csv('penguins_raw.csv')

```

```{r cleaning, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# drop a column that has no values
dat <- dat %>% 
  select(-Comments)

# filter out rows with no sex
dat <- dat %>% 
  filter(!is.na(Sex))

# str(knitr::opts_chunk$get())

```

# Species by Island

```{r bar, echo=FALSE, fig.width=12, message=FALSE, warning=FALSE, paged.print=FALSE}

# bar plot
dat %>%
  ggplot(aes(x = Island, fill = Species)) +
  geom_bar() + 
  labs(
    title = "Where Do They Live?",
    subtitle = "by Island",
    caption = "data from palmerpenguines R package"
  )

```

<br>

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results='asis'}
# have a remote analyst write content that you can source into this doc
cat(read_lines(file = "interpret_islands.txt"))
```

<br>

# Understanding Penguin Anatomy

```{r scatter, echo=FALSE, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}

# scatter plot, add titles
length_mass <- dat %>% 
  ggplot(aes(x = `Flipper Length (mm)`, y = `Body Mass (g)`, color = Species)) +
  geom_point(alpha = .4) +
  labs(
    title = "Is Flipper Length Associated With Body Mass?",
    subtitle = "by species",
    caption = "data from palmerpenguines R package"
  ) +
  theme_light()

# lets make the last one an interactive javascript-based plot,
# where the user can hover and hide lines
plotly::ggplotly(length_mass)

```

<br>

# Summary Table
We can see that for Adelie, their culmen length is getting longer on Biscoe Island but shorter on Dream Island.

```{r table, echo=FALSE, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}

# make a table of our data
# but let's summarize by year, so first make a year column
dat <- dat %>%
  dplyr::arrange(`Date Egg`) %>% 
  mutate(Year = year(`Date Egg`),
         Year = as.factor(Year))

# table using gt package
dat %>% 
  janitor::clean_names() %>% 
  group_by(species, island, year) %>% # order here will influence table output
  summarise(across(culmen_length_mm:body_mass_g, mean)) %>%
  select(species, island, year, everything()) %>% 
  dplyr::arrange(species, island, year) %>% 
  gt() %>%
  tab_header(
    title = "Penguin Anatomical Changes",
    subtitle = "By species, island, and year"
  ) %>%
  fmt_number(
    columns = culmen_length_mm:body_mass_g,
    decimals = 1
  )

```

[more about the gt package](https://gt.rstudio.com/index.html)

<br> <br>

## References

Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package version 0.1.0. <https://allisonhorst.github.io/palmerpenguins/>
